Change the custom yaml file for a Berksfile to manage the cookbooks

diff --git a/bin/lxc-provision b/bin/lxc-provision
--- a/bin/lxc-provision
+++ b/bin/lxc-provision
@@ -10,6 +10,7 @@ Usage:
 Options:
     -h, --help                 Show this help
     -n, --name <name>          LXC container's name
+    -b, --berksfile <path>     The path to the project's Berksfile
     -- <chef-solo parameters>  Any parameters to pass to the chef-solo
                                (e.g. '-l debug')
 
@@ -27,6 +28,10 @@ do
         name=$2
         shift 2
         ;;
+    -b|--berksfile)
+        berksfile=$2
+        shift 2
+        ;;
     --)
         shift 1
         params=$@
@@ -39,10 +44,21 @@ do
 done
 
 if [ -z $name ] || [ ! -d /var/lib/lxc/${name} ]; then
-  echo "You need to pass a valid name of a container"
+  echo "ERROR: You need to pass a valid name of a container"
   usage
   exit 1
 fi
 
-lxc-ssh -n $name -c "LC_ALL=C sudo /opt/chef/bin/chef-solo -c /etc/chef/solo.rb $params"
+if [ -z $berksfile ] || [ ! -f $berksfile ]; then
+  echo "ERROR: You must pass a valid path to the Berksfile"
+  usage
+  exit 1
+fi
+
+username=$(< /var/lib/lxc/${name}/user)
+cp $berksfile /var/lib/lxc/${name}/rootfs/home/${username}/
+
+cmd="sudo /opt/chef/embedded/bin/berks install -b Berksfile -p /var/chef-solo/cookbooks/ ;\
+LC_ALL=C sudo /opt/chef/bin/chef-solo -c /etc/chef/solo.rb $params"
+lxc-ssh -n $name -c $cmd
 
